import { IsNotEmpty, IsString, Length } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class MfaVerifyDto {
  @ApiProperty({ example: '123456', description: '6-digit TOTP code generated by authenticator app' })
  @IsString()
  @IsNotEmpty()
  @Length(6, 6, { message: 'TOTP code must be exactly 6 digits' })
  code!: string;

  @ApiProperty({ description: 'The TOTP secret key generated during MFA setup' })
  @IsString()
  @IsNotEmpty()
  secret!: string;
}
